api_platform:
    title: 'Pathfinder DB'
    version: 0.0.1
    show_webby: false
    path_segment_name_generator: 'api_platform.path_segment_name_generator.dash'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
