#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'static/index.html.twig'
    maxAge:    86400
    sharedAge: 86400

classes:
  path: /classes
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'static/classes.html.twig'
    maxAge:    86400
    sharedAge: 86400

magic:
  path: /magic
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'static/magic.html.twig'
    maxAge:    86400
    sharedAge: 86400


contribute:
  path: /contribute
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'static/contribute.html.twig'
    maxAge:    86400
    sharedAge: 86400

