# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  projectname: PathfinderDB
  paypallink: https://paypal.me/joern
  copyrightNotice:
    author: 'Jörn Meyer'
    github: https://github.com/joerncodes/pathfinderdb
    notice: '%projectname% was coded by a single guy. If you find it helpful, please consider donating a buck or two!'
    support:
      paypal: '%paypallink%'
    paizo: "Paizo Inc., Paizo, the Paizo golem logo, Pathfinder, the Pathfinder logo, Pathfinder Society, Starfinder, the Starfinder logo, GameMastery, and Planet Stories are registered trademarks of Paizo Inc. The Pathfinder Roleplaying Game, Pathfinder Campaign Setting, Pathfinder Adventure Path, Pathfinder Adventure Card Game, Pathfinder Player Companion, Pathfinder Modules, Pathfinder Tales, Pathfinder Battles, Pathfinder Legends, Pathfinder Online, Starfinder Adventure Path, PaizoCon, RPG Superstar, The Golem's Got It, Titanic Games, the Titanic logo, and the Planet Stories planet logo are trademarks of Paizo Inc. Dungeons & Dragons, Dragon, Dungeon, and Polyhedron are registered trademarks of Wizards of the Coast, Inc., a subsidiary of Hasbro, Inc., and have been used by Paizo Inc. under license. Most product names are trademarks owned or used under license by the companies that publish those products; use of such names without mention of trademark status should not be construed as a challenge to such status."

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Domain\PropertySorting\SorterInterface:
            tags:
                - { name: property.sorter }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Domain\Markdown\Content:
        arguments:
            $contentPath: '%kernel.project_dir%/content'

    App\Domain\PropertySorting\PropertySorter:
        arguments: [!tagged property.sorter ]

    App\Domain\EventSubscriber\CopyrightRespondListener:
        arguments:
          $copyrightNotice: '%copyrightNotice%'
